/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        secondary: "#4e45d5",
        "surface-container-low": "#f2f3ff",
        "tertiary-container": "#006a7c",
        error: "#ba1a1a",
        "secondary-fixed": "#e3dfff",
        "on-surface": "#131b2e",
        "secondary-container": "#6860ef",
        "on-surface-variant": "#464555",
        "on-error-container": "#93000a",
        "on-background": "#131b2e",
        "secondary-fixed-dim": "#c3c0ff",
        "primary-fixed": "#e2dfff",
        "primary-container": "#4f46e5",
        "on-primary-fixed": "#0f0069",
        "tertiary-fixed": "#acedff",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        background: "#faf8ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-secondary-container": "#fffbff",
        tertiary: "#00505f",
        "surface-container-high": "#e2e7ff",
        "inverse-primary": "#c3c0ff",
        outline: "#777587",
        "on-secondary": "#ffffff",
        "inverse-surface": "#283044",
        "on-tertiary-fixed": "#001f26",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-primary": "#ffffff",
        surface: "#faf8ff",
        "surface-tint": "#4d44e3",
        "surface-container-highest": "#dae2fd",
        primary: "#3525cd",
        "primary-fixed-dim": "#c3c0ff",
        "on-secondary-fixed": "#100069",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container": "#eaedff",
        "surface-bright": "#faf8ff",
        "outline-variant": "#c7c4d8",
        "on-secondary-fixed-variant": "#372abf",
        "on-tertiary-container": "#93e8ff",
        "surface-variant": "#dae2fd",
        "inverse-on-surface": "#eef0ff",
        "on-primary-container": "#dad7ff",
        "surface-dim": "#d2d9f4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-2xl": "3rem",
        margin: "2rem",
        "space-xs": "0.25rem",
        gutter: "1.5rem",
        "margin-mobile": "1rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "gutter-mobile": "1rem",
        "space-md": "1rem",
      },
      fontFamily: {
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "800" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
